version: '2'
services:
  web:
    container_name: somedockerapp_nginx
    image: nginx:latest
    ports:
      - "55080:80"
    volumes:
      - ./code:/code
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: somedockerapp_db
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: somedockerapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  php:
    container_name: somedockerapp_php
    build:
      context: .
      dockerfile: phpserver.dockerfile
    volumes:
      - ./code:/code
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/10-xdebug.ini
      - ./server-logs/xdebug-profiles:/var/www/xdebug-profiles
      - ./server-logs/xdebug-traces:/var/www/xdebug-traces
  memcached:
    container_name: somedockerapp_memcached
    image: memcached:1.6.5
  elastic:
    container_name: somedockerapp_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  logstash:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - elastic
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
      - ./code/:/code/
    image: docker.elastic.co/logstash/logstash:7.6.2
  kibana:
    ports:
      - "55601:5601"
    depends_on:
      - elastic
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml